/**
 * SldCanvas — web-only pan+zoom SVG renderer. Loads the SVG string from
 * SldProvider and injects via dangerouslySetInnerHTML on a positioned div.
 * Mouse wheel zooms (toward cursor); drag pans.
 *
 * Per architecture lock: the SVG is generated by edp-api per deployment.
 * The HMI is read-only — it overlays live state via SVG data-* attributes
 * matched against MQTT topics (overlay path lands when SVG carries real ids).
 *
 * Native render path TBD — react-native-svg doesn't accept an arbitrary
 * SVG string; will need WebView or rasterize. Tracked in step 11 follow-up.
 */

import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useSldSvg } from "../../../../data/sld/useSldSvg";
import { useTheme } from "../../../../theme/ThemeProvider";
import { useOperatingEnvelope } from "../../../../data/envelope/useOperatingEnvelope";

const MIN_SCALE = 0.25;
const MAX_SCALE = 6;
const WHEEL_ZOOM_FACTOR = 1.0015;
/** Leave a 24px margin between the SVG and the canvas edge on fit. */
const FIT_PADDING = 24;

/**
 * Patch an SVG markup string with explicit width/height attrs derived from
 * its viewBox. edp-api's generator emits viewBox-only SVGs (correct, lets
 * the consumer size); the HMI is the consumer, so we size here.
 */
function withExplicitSize(svg: string): string {
  const viewBoxMatch = /viewBox\s*=\s*"([^"]+)"/.exec(svg);
  if (!viewBoxMatch || viewBoxMatch[1] === undefined) return svg;
  const parts = viewBoxMatch[1].split(/\s+/).map(Number);
  if (parts.length !== 4 || parts.some((n) => !Number.isFinite(n))) return svg;
  const w = parts[2];
  const h = parts[3];
  if (w === undefined || h === undefined) return svg;
  const svgTagMatch = /<svg\b[^>]*>/.exec(svg);
  if (svgTagMatch && /\b(width|height)\s*=/.test(svgTagMatch[0])) return svg;
  return svg.replace(
    /<svg\b/,
    `<svg width="${w}" height="${h}"`,
  );
}

interface Transform {
  x: number;
  y: number;
  scale: number;
}

/**
 * Compute the transform that fits an SVG of `svgW`×`svgH` inside a viewport
 * of `vpW`×`vpH`, with `FIT_PADDING` margin on every side. Scale is clamped
 * to [MIN_SCALE, MAX_SCALE]; result is centered.
 */
function fitTransform(
  svgW: number,
  svgH: number,
  vpW: number,
  vpH: number,
): Transform {
  const availableW = Math.max(1, vpW - FIT_PADDING * 2);
  const availableH = Math.max(1, vpH - FIT_PADDING * 2);
  const scale = Math.max(
    MIN_SCALE,
    Math.min(MAX_SCALE, Math.min(availableW / svgW, availableH / svgH)),
  );
  return {
    scale,
    x: (vpW - svgW * scale) / 2,
    y: (vpH - svgH * scale) / 2,
  };
}

/** Pull the natural svg dimensions from its viewBox. */
function svgDims(svg: string): { w: number; h: number } | null {
  const m = /viewBox\s*=\s*"([^"]+)"/.exec(svg);
  if (!m || m[1] === undefined) return null;
  const parts = m[1].split(/\s+/).map(Number);
  if (parts.length !== 4 || parts.some((n) => !Number.isFinite(n))) return null;
  const w = parts[2];
  const h = parts[3];
  if (w === undefined || h === undefined) return null;
  return { w, h };
}

function stateTokenLabel(doeState: string): string {
  if (doeState === "stale") return "STALE";
  if (doeState === "invalid") return "INVALID";
  if (doeState === "comm-fail") return "COMM FAIL";
  if (doeState === "island") return "ISLAND";
  return "OK";
}

export function SldCanvas(): React.ReactElement {
  const t = useTheme();
  const { status, svg, error } = useSldSvg();
  const envelope = useOperatingEnvelope();
  const containerRef = useRef<HTMLDivElement | null>(null);
  const [tx, setTx] = useState<Transform | null>(null);
  const dragRef = useRef<{ startX: number; startY: number; baseX: number; baseY: number } | null>(null);

  const dims = useMemo(() => (svg ? svgDims(svg) : null), [svg]);

  // Reason: compute fit transform once we have the SVG + the container's
  // actual measured size. Re-fits on container resize.
  useEffect(() => {
    const el = containerRef.current;
    if (!el || !dims) return;
    const apply = (): void => {
      const r = el.getBoundingClientRect();
      setTx(fitTransform(dims.w, dims.h, r.width, r.height));
    };
    apply();
    const ro = new ResizeObserver(apply);
    ro.observe(el);
    return (): void => ro.disconnect();
  }, [dims]);

  // Reason: edp-api emits structural slots (data-role="poi" + state-label
  // / state-token / primary-value text placeholders). HMI fills them with
  // live values from useOperatingEnvelope. Runs whenever envelope state
  // changes OR the SVG is (re)injected.
  useEffect(() => {
    const root = containerRef.current?.querySelector(".sld-svg-root");
    if (!root) return;
    const primary = root.querySelector('[data-role="poi"] [data-region="primary-value"]');
    if (primary) primary.textContent = envelope.settlement;
    const token = root.querySelector('[data-role="poi"] [data-region="state-token"]');
    if (token) {
      token.textContent = stateTokenLabel(envelope.doeState);
      // Color elevation per UTILITY-FEEDS §7 severity mapping.
      const color =
        envelope.doeState === "ok" || envelope.doeState === "island"
          ? t.textSoft
          : envelope.doeState === "stale"
            ? t.statusWarn
            : t.statusAlarm;
      (token as SVGElement).setAttribute("fill", color);
    }
  }, [envelope.settlement, envelope.doeState, t, svg, tx]);

  const reset = useCallback((): void => {
    const el = containerRef.current;
    if (!el || !dims) return;
    const r = el.getBoundingClientRect();
    setTx(fitTransform(dims.w, dims.h, r.width, r.height));
  }, [dims]);

  const onWheel = useCallback((e: React.WheelEvent<HTMLDivElement>) => {
    e.preventDefault();
    const rect = e.currentTarget.getBoundingClientRect();
    const cx = e.clientX - rect.left;
    const cy = e.clientY - rect.top;
    setTx((prev) => {
      if (!prev) return prev;
      const factor = WHEEL_ZOOM_FACTOR ** -e.deltaY;
      const nextScale = Math.max(MIN_SCALE, Math.min(MAX_SCALE, prev.scale * factor));
      // Reason: keep the point under the cursor stationary while zooming.
      const ratio = nextScale / prev.scale;
      return {
        scale: nextScale,
        x: cx - (cx - prev.x) * ratio,
        y: cy - (cy - prev.y) * ratio,
      };
    });
  }, []);

  const onMouseDown = useCallback((e: React.MouseEvent<HTMLDivElement>): void => {
    if (!tx) return;
    dragRef.current = {
      startX: e.clientX,
      startY: e.clientY,
      baseX: tx.x,
      baseY: tx.y,
    };
  }, [tx]);

  const onMouseMove = useCallback((e: React.MouseEvent<HTMLDivElement>): void => {
    const d = dragRef.current;
    if (!d) return;
    setTx((prev) => (
      prev ? { ...prev, x: d.baseX + (e.clientX - d.startX), y: d.baseY + (e.clientY - d.startY) } : prev
    ));
  }, []);

  const onMouseUp = useCallback((): void => {
    dragRef.current = null;
  }, []);

  const sizedSvg = useMemo(() => (svg ? withExplicitSize(svg) : null), [svg]);

  const overlayLabel = (() => {
    if (status === "loading") return "Loading diagram…";
    if (status === "error") return `Error: ${error ?? "unknown"}`;
    if (!svg) return "Diagram unavailable";
    return null;
  })();

  return (
    <div
      ref={containerRef}
      data-comp="SldCanvas"
      onWheel={onWheel}
      onMouseDown={onMouseDown}
      onMouseMove={onMouseMove}
      onMouseUp={onMouseUp}
      onMouseLeave={onMouseUp}
      onDoubleClick={reset}
      style={{
        position: "relative",
        flex: 1,
        overflow: "hidden",
        backgroundColor: t.bg,
        cursor: dragRef.current ? "grabbing" : "grab",
        userSelect: "none",
        touchAction: "none",
      }}
    >
      {sizedSvg && tx && (
        <div
          dangerouslySetInnerHTML={{ __html: sizedSvg }}
          // Reason: edp-api's SVG uses fill="currentColor" / stroke="currentColor"
          // EVERYWHERE so the consumer (us) picks contrast via descendant CSS.
          // Bodies → t.text, labels → t.surface (high contrast against the body),
          // status-indicator → t.statusOk by default (overlay flips later).
          className="sld-svg-root"
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            transform: `translate(${tx.x}px, ${tx.y}px) scale(${tx.scale})`,
            transformOrigin: "0 0",
            color: t.text,
            fontFamily: t.fontLabel,
            fontSize: 11,
          }}
        />
      )}
      <style>{`
        /* Device body: filled surface with a domain-neutral stroke. */
        .sld-svg-root [data-region="body"] {
          fill: ${t.surface};
          stroke: ${t.border};
          stroke-width: 1.5;
        }
        /* Device-node group hover hint — desktop only. */
        .sld-svg-root [data-comp="device-node"]:hover [data-region="body"] {
          stroke: ${t.accent};
          stroke-width: 2;
        }
        /* Label names: bold, full-text color. */
        .sld-svg-root [data-region="label-name"] {
          fill: ${t.text};
          font-weight: 700;
          font-size: 11px;
        }
        /* Template slug: smaller, softer. */
        .sld-svg-root [data-region="label-template"] {
          fill: ${t.textSoft};
          font-size: 9px;
          font-weight: 500;
          letter-spacing: 0.5px;
          text-transform: uppercase;
        }
        /* Status indicator: bigger dot + soft halo via stroke. */
        .sld-svg-root [data-region="status-indicator"] {
          fill: ${t.statusOk};
          stroke: ${t.surface};
          stroke-width: 1.5;
          r: 5;
        }
        /* Bus paths: thick + capped, drawn behind device groups via opacity. */
        .sld-svg-root [data-comp="bus"] {
          stroke: ${t.textMid};
          stroke-width: 3;
          stroke-linecap: round;
          fill: none;
          opacity: 0.55;
        }
        /* DC vs AC bus get distinct dasharrays for at-a-glance type read. */
        .sld-svg-root [data-comp="bus"][data-bus-type="ac"] {
          stroke-dasharray: 6 3;
        }
        /* Hit-area transparent but pointer-friendly. */
        .sld-svg-root [data-region="hit-area"] { cursor: pointer; }

        /* ── Utility-side feed styling (per UTILITY-FEEDS.md §5) ───────────── */

        /* POI revenue meter — emphasize as the settlement node. Accent
           border + dedicated primary-value slot above name; state row below. */
        .sld-svg-root [data-role="poi"] [data-region="body"] {
          stroke: ${t.accent};
          stroke-width: 2;
        }
        /* Reposition the name into the slot above center so the primary-value
           slot (y=-2 in source) becomes the top reading. */
        .sld-svg-root [data-role="poi"] [data-region="label-name"] {
          font-size: 9px;
          fill: ${t.textSoft};
          transform: translateY(8px);
        }
        .sld-svg-root [data-role="poi"] [data-region="primary-value"] {
          fill: ${t.text};
          font-weight: 700;
          font-size: 11px;
          transform: translateY(-4px);
        }
        .sld-svg-root [data-role="poi"] [data-region="state-label"] {
          fill: ${t.textSoft};
          font-size: 7px;
          font-weight: 600;
          letter-spacing: 0.4px;
          text-transform: uppercase;
          transform: translateY(2px);
        }
        .sld-svg-root [data-role="poi"] [data-region="state-token"] {
          font-size: 7px;
          font-weight: 700;
          letter-spacing: 0.3px;
          text-transform: uppercase;
          transform: translateY(2px);
        }
        /* Hide the template-slug subtitle on POI — primary-value already
           occupies that vertical real estate. */
        .sld-svg-root [data-role="poi"] [data-region="label-template"] {
          display: none;
        }

        /* DLR badge — compact treatment via reduced label sizing. The
           graphviz layout still positions it; visual scale collapses it. */
        .sld-svg-root [data-role="dlr-badge"] [data-region="body"] {
          stroke: ${t.textSoft};
          stroke-width: 1;
          stroke-dasharray: 3 2;
        }
        .sld-svg-root [data-role="dlr-badge"] [data-region="label-name"] {
          font-size: 9px;
          fill: ${t.textSoft};
        }
        .sld-svg-root [data-role="dlr-badge"] [data-region="label-template"] {
          display: none;
        }
      `}</style>
      {overlayLabel && (
        <div
          style={{
            position: "absolute",
            inset: 0,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            pointerEvents: "none",
            color: t.textSoft,
            fontFamily: t.fontLabel,
            fontSize: 12,
            letterSpacing: 0.18,
            textTransform: "uppercase",
          }}
        >
          {overlayLabel}
        </div>
      )}
      <div
        style={{
          position: "absolute",
          right: 12,
          bottom: 12,
          color: t.textSoft,
          fontFamily: t.fontLabel,
          fontSize: 10,
          letterSpacing: 0.15,
          textTransform: "uppercase",
          opacity: 0.65,
        }}
      >
        {tx ? `${(tx.scale * 100).toFixed(0)}%` : "—"} · double-click resets
      </div>
    </div>
  );
}
