// gallery-sld.jsx — SLD (Single Line Diagram) showcase
// Static SVG topology with named device IDs, bus states, breaker symbols,
// particle flow (energized buses), maintenance overlay.
//
// In production, the SLD SVG is generated by edp-api per deployment; this
// gallery component is a HAND-DRAWN reference showing the visual contract:
// what tokens drive each element, what states each element has, where
// particles flow, how breaker symbols render, etc.

// ─── Single device node ────────────────────────────────────────────────
function SLDNode({ t, x, y, w = 80, h = 56, label, status = 'ok', acknowledged = true, kw, maintenance, moduleType }) {
  const sevColor =
    maintenance ? t.statusMaintenance :
    status === 'fire' ? t.statusFire :
    status === 'alarm' ? t.statusAlarm :
    status === 'warn' ? t.statusWarn :
    status === 'offline' ? t.statusOffline :
    t.statusOk;
  const domainColor =
    moduleType === 'bess'    ? t.colorBess :
    moduleType === 'compute' ? t.colorCompute :
    moduleType === 'thermal' ? t.colorThermal :
    moduleType === 'grid'    ? t.colorGrid :
    t.text;
  const isUnack = !acknowledged && (status === 'warn' || status === 'alarm');
  const pulse = status === 'fire';

  return (
    <g transform={`translate(${x} ${y})`}>
      {/* node body */}
      <rect x={-w/2} y={-h/2} width={w} height={h} rx="4"
            fill={maintenance ? t.panel : t.surface}
            stroke={sevColor}
            strokeWidth={maintenance ? 1.5 : 1}
            strokeDasharray={maintenance ? '3 2' : 'none'}/>
      {/* domain accent strip on the left */}
      {!maintenance && (
        <rect x={-w/2} y={-h/2} width={3} height={h} fill={domainColor}/>
      )}
      {/* label */}
      <text x="0" y={-h/2 + 16} textAnchor="middle"
            fontFamily={t.fontLabel} fontSize="10" fontWeight="700"
            letterSpacing="1" fill={t.text}>{label}</text>
      {/* kW reading */}
      {kw != null && (
        <text x="0" y={-h/2 + 32} textAnchor="middle"
              fontFamily={t.fontLabel} fontSize="11" fontWeight="500"
              fill={t.textMid} style={{ fontVariantNumeric: 'tabular-nums' }}>{kw} kW</text>
      )}
      {/* status indicator dot (top-right) — flashes when unack, pulses on fire */}
      <circle cx={w/2 - 7} cy={-h/2 + 7} r="3.5" fill={sevColor}>
        {isUnack && <animate attributeName="opacity" values="1;0.3;1" dur="1.4s" repeatCount="indefinite"/>}
        {pulse && <animate attributeName="opacity" values="1;0.6;1" dur="0.8s" repeatCount="indefinite"/>}
      </circle>
      {/* wrench overlay for maintenance */}
      {maintenance && (
        <g transform={`translate(${w/2 - 10} ${h/2 - 10})`}>
          <circle cx="0" cy="0" r="8" fill={t.statusMaintenance} opacity="0.2"/>
          <path d="M-3 -3 a 2 2 0 0 1 2.5 2.5 L 4 5 a 1.5 1.5 0 0 1 -2 -2 Z"
                fill={t.statusMaintenance}/>
        </g>
      )}
    </g>
  );
}

// ─── Bus line with particle flow ───────────────────────────────────────
function SLDBus({ t, x1, y1, x2, y2, energized = true, domain = 'grid', kw = 100, maintenance = false }) {
  const color = !energized || maintenance ? t.statusOffline :
                domain === 'bess'    ? t.colorBess :
                domain === 'compute' ? t.colorCompute :
                domain === 'grid'    ? t.colorGrid :
                t.text;
  // 3 particles per bus, animated along the path
  const len = Math.hypot(x2 - x1, y2 - y1);
  const speed = energized && !maintenance ? Math.max(6, Math.min(20, 200 / Math.abs(kw))) : 0;

  return (
    <g>
      <line x1={x1} y1={y1} x2={x2} y2={y2}
            stroke={color} strokeWidth="2"
            strokeDasharray={maintenance ? '4 3' : 'none'}/>
      {energized && !maintenance && [0, 0.33, 0.66].map((offset, i) => (
        <circle key={i} r="2.5" fill="#fff" opacity="0.85">
          <animateMotion dur={`${speed}s`} repeatCount="indefinite" begin={`-${speed * offset}s`}
                         path={`M${x1} ${y1} L${x2} ${y2}`}/>
        </circle>
      ))}
    </g>
  );
}

// ─── Breaker symbol ────────────────────────────────────────────────────
function SLDBreaker({ t, x, y, open = false }) {
  return (
    <g transform={`translate(${x} ${y})`}>
      {/* circle ring */}
      <circle cx="0" cy="0" r="7" fill={t.surface} stroke={t.text} strokeWidth="1.5"/>
      {/* closed: horizontal bar | open: angled gap */}
      {open ? (
        <line x1="-4" y1="0" x2="4" y2="-5" stroke={t.text} strokeWidth="1.5" strokeLinecap="round"/>
      ) : (
        <line x1="-4" y1="0" x2="4" y2="0" stroke={t.text} strokeWidth="1.5" strokeLinecap="round"/>
      )}
    </g>
  );
}

// ─── Composed showcase ─────────────────────────────────────────────────
function SLDShowcase({ t }) {
  const W = 640, H = 320;
  return (
    <div style={{ width: '100%', display: 'flex', flexDirection: 'column', gap: SPACE[3] }}>
      <svg viewBox={`0 0 ${W} ${H}`} style={{
        width: '100%', height: 'auto',
        background: t.surface, border: `1px solid ${t.border}`, borderRadius: RADIUS[3],
      }}>
        {/* SIM watermark */}
        <text x={W/2} y={H/2 + 8} textAnchor="middle" opacity="0.07"
              fontFamily={t.fontHeading} fontSize="72" fontWeight="500"
              fill={t.statusSim} letterSpacing="6">SIM</text>

        {/* horizontal AC bus (grid) at y=80 */}
        <SLDBus t={t} x1={60} y1={80} x2={W - 60} y2={80} energized domain="grid" kw={142}/>

        {/* GRID + breaker on left */}
        <SLDNode t={t} x={60} y={80} w={90} h={50} label="GRID-01" moduleType="grid" kw={142}/>
        <SLDBreaker t={t} x={130} y={80} open={false}/>

        {/* Compute branches off AC bus */}
        <SLDBus t={t} x1={220} y1={80} x2={220} y2={150} energized domain="compute" kw={184}/>
        <SLDBus t={t} x1={350} y1={80} x2={350} y2={150} energized domain="compute" kw={92}/>
        <SLDBus t={t} x1={480} y1={80} x2={480} y2={150} energized={false} domain="compute"/>

        <SLDNode t={t} x={220} y={180} w={90} h={60} label="CMP-S01" moduleType="compute" kw={92} status="ok"/>
        <SLDNode t={t} x={350} y={180} w={90} h={60} label="CMP-S04" moduleType="compute" kw={92} status="warn" acknowledged={false}/>
        <SLDNode t={t} x={480} y={180} w={90} h={60} label="CMP-S99" moduleType="compute" status="offline"/>

        {/* DC bus on right, lower */}
        <SLDBus t={t} x1={60} y1={260} x2={W - 200} y2={260} energized domain="bess" kw={42}/>
        <SLDBreaker t={t} x={130} y={260} open={false}/>

        {/* BESS modules on DC bus */}
        <SLDNode t={t} x={220} y={260} w={90} h={50} label="BESS-01" moduleType="bess" kw={-42} status="ok"/>
        <SLDNode t={t} x={350} y={260} w={90} h={50} label="BESS-02" moduleType="bess" kw={-38} status="alarm" acknowledged={false}/>

        {/* Thermal, isolated (maintenance) */}
        <SLDNode t={t} x={W - 80} y={260} w={90} h={50} label="CDU-01" moduleType="thermal" maintenance/>
        <SLDBus t={t} x1={W - 200} y1={260} x2={W - 130} y2={260} energized={false} domain="thermal" maintenance/>
      </svg>

      {/* Legend */}
      <div style={{
        display: 'flex', flexWrap: 'wrap', gap: SPACE[3], padding: SPACE[3],
        background: t.panel, border: `1px solid ${t.borderSoft}`, borderRadius: RADIUS[2],
      }}>
        {[
          { color: t.colorGrid,    label: 'Grid bus (energized · particles flow)' },
          { color: t.colorCompute, label: 'Compute bus' },
          { color: t.colorBess,    label: 'BESS DC bus' },
          { color: t.statusOffline, label: 'De-energized · static' },
          { color: t.statusMaintenance, label: 'Maintenance · dashed + wrench' },
        ].map((l, i) => (
          <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <span style={{
              width: 16, height: 2, background: l.color,
              borderRadius: 1, flexShrink: 0,
            }}/>
            <span style={{
              fontFamily: t.fontLabel, fontSize: 10, color: t.textMid,
              letterSpacing: 0.05,
            }}>{l.label}</span>
          </div>
        ))}
      </div>

      {/* Breaker variants */}
      <div style={{
        display: 'flex', gap: SPACE[4], alignItems: 'center', padding: SPACE[3],
        background: t.panel, border: `1px solid ${t.borderSoft}`, borderRadius: RADIUS[2],
      }}>
        <span style={{
          fontFamily: t.fontLabel, fontSize: 9, color: t.textSoft,
          letterSpacing: 0.18, textTransform: 'uppercase', fontWeight: 600,
        }}>Breaker symbol</span>
        <svg width="40" height="24" viewBox="-20 -12 40 24">
          <SLDBreaker t={t} x={0} y={0} open={false}/>
        </svg>
        <span style={{ fontFamily: t.fontLabel, fontSize: 11, color: t.textMid }}>CLOSED</span>
        <svg width="40" height="24" viewBox="-20 -12 40 24">
          <SLDBreaker t={t} x={0} y={0} open={true}/>
        </svg>
        <span style={{ fontFamily: t.fontLabel, fontSize: 11, color: t.textMid }}>OPEN</span>
      </div>
    </div>
  );
}

Object.assign(window, {
  SLDNode, SLDBus, SLDBreaker, SLDShowcase,
});
